name: Immunefi-Snapshot-Script

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"  # 12:00 AM IST
    - cron: "30 10 * * *"  # 4:00 PM IST

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/runner/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install ggrep
        run: brew install grep

      - name: Verify ggrep installation
        run: ggrep --version

      - name: Run scrapper.sh script
        run: |
          git config user.name "github-actions[bot]"
          chmod +x ./scrapper.sh
          ./scrapper.sh
        shell: bash
